# Generated by Django 3.1.6 on 2021-05-29 04:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='ct_dongia',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='ct_soluong',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='dh',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='sp',
        ),
        migrations.AddField(
            model_name='donhang',
            name='diachi',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='donhang',
            name='kh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banhang.khachhang'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='ngay',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='donhang',
            name='sdt',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='donhang',
            name='trangthai',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='chitietdonhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_soluong', models.IntegerField(default=1)),
                ('ct_dongia', models.IntegerField(default=0)),
                ('dh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banhang.donhang')),
                ('sp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banhang.sanpham')),
            ],
        ),
    ]
